# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorldRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic_world.User')),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userworldrelation',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic_world.World'),
        ),
        migrations.AddField(
            model_name='user',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic_world.World'),
        ),
    ]
