# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('logic_world', '0002_auto_20160213_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('auth_user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('world_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='userworldrelation',
            name='world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_world.World'),
        ),
        migrations.AlterField(
            model_name='world',
            name='user_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userworldrelation',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_world.CustomUser'),
        ),
        migrations.AddField(
            model_name='world',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_world.CustomUser'),
        ),
    ]
