# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_world', '0004_auto_20160215_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='output',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value',
        ),
        migrations.AddField(
            model_name='world',
            name='world_name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AddField(
            model_name='worldelement',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
