language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.9.2

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION

# command to run tests
script: python manage.py test
